rnk_el_finder_backend:
    pattern:  /rnk_el_finder_backend
    defaults: { _controller: RNKElFinderBundle:ElFinder:backend }

rnk_el_finder_show:
    pattern: /rnk_el_finder_show
    defaults: { _controller: RNKElFinderBundle:ElFinder:show }